### ISSUE TITLE
Todo...

### ISSUE THREAD

**Issue by jankatins** [jankatins/knitpy#39]
## ToDo
- [ ] Implement a R engine/kernel
- [ ] Implement setting a kernel name in the yaml block
- [ ] Implement eval'ing the code block arguments
- [ ] Make sure that inline strings (+unicode on py27!) are not getting quotes...
- [ ] implement more args for codeblocks -> image size, image titles, etc
- [ ] use metadata in keep_md output (like rmarkdown does...)  should output `<title>\n<author>\n<date>` before the rest;  remove the first yaml block, but keep everything else...
- [ ] refactor the parsing, so that it is line based  -> errors make more sense, because it knows the line ("block starting at line....")
- [ ] make output format configureable
- [ ] sane naming scheme for plots/... -> subdirs, naming-by-chunk-name -> mostly done
- [ ] Documentation: what works? what is not supported?; differences to rmarkdown? / knitr
- [ ] Investigate https://github.com/jgm/pandocfilters as internal temp format -> would remove 250 lines of code...
- [ ] move python parser in knitpy.py into the python engine (or remove completely -> Only the last lines resturn will aut display) 
## unittests...
- [x] should probably be done by a simple dir + textfiles ala test_input.pymd, test_output.md
- [ ] codeblocks + inline
- [ ] yaml
- [ ] errors
- [ ] pandoc caller (via mocks?)
## done
- logging for debugging...
- text/plain of display_data -> should be displayed first and then data
- refactoring: execution/output -> should be models after execution preprocessor
- YAML metadata
- refactoring: entangle knitpy the app and knitpy the converter
  -> app should call the converter
- refactoring: entangle the documents from the application logic
  -> app logic into "knitpy the converter"
  -> document specific logic/ things into the documents
  -> language specific ones into the "engines"
  => This is currently not so clean: doc.parse(...) vs self.convert(input, output)
- merge input cells for cells without output

**Comment by JanSchulz** [comment]
Note to self: checkout brnach "r-stuff+fixes"
